# Generated by Django 6.0.4 on 2026-05-12 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobseeker', '0002_alter_application_resume_jobseekerprofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='education',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='experience_years',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='github',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='resume',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='jobseekerprofile',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='jobseekerprofile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='application',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='jobseekerprofile',
            name='skills',
            field=models.TextField(blank=True, default=''),
        ),
    ]
