# Generated by Django 6.0.5 on 2026-05-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("companyName", models.CharField(max_length=50)),
                ("website", models.TextField(max_length=300)),
                ("location", models.CharField(max_length=50)),
                ("description", models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name="Opportunit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.TextField(max_length=100)),
                ("phone", models.CharField(max_length=15)),
                ("location", models.CharField(max_length=100)),
                ("experience", models.PositiveBigIntegerField()),
                ("salary_min", models.PositiveIntegerField()),
                ("salary_max", models.PositiveIntegerField()),
                ("responsibilities", models.TextField(max_length=1000)),
                ("requirements", models.TextField(max_length=1000)),
                ("postedDate", models.DateTimeField(auto_now=True)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("FULL_TIME", "Full-Time"),
                            ("PART_TIME", "Part-Time"),
                            ("FREELANCE", "Freelance"),
                        ],
                        default="FULL_TIME",
                        max_length=20,
                    ),
                ),
            ],
        ),
    ]
