# Generated by Django 6.0.5 on 2026-05-10 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Opportunit",
            new_name="Opportunity",
        ),
    ]
