# Generated by Django 6.0.5 on 2026-05-10 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0002_rename_opportunit_opportunity"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="status",
            field=models.CharField(
                choices=[("OPEN", "Open"), ("CLOSED", "Closed"), ("DRAFT", "Draft")],
                default="OPEN",
                max_length=10,
            ),
        ),
    ]
