# Generated by Django 6.0.5 on 2026-05-10 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0003_opportunity_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opportunity",
            name="phone",
        ),
    ]
