# Generated by Django 6.0.5 on 2026-05-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0004_remove_opportunity_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="CompanyName",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
