# Generated by Django 6.0.5 on 2026-05-10 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0005_opportunity_companyname"),
    ]

    operations = [
        migrations.RenameField(
            model_name="opportunity",
            old_name="CompanyName",
            new_name="companyName",
        ),
        migrations.AddField(
            model_name="opportunity",
            name="jobDescription",
            field=models.TextField(max_length=500, null=True),
        ),
    ]
