# Generated by Django 6.0.4 on 2026-05-12 19:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_rename_companyname_opportunity_companyname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='Company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='opportunities', to='company.company'),
        ),
    ]
