# Generated by Django 6.0.5 on 2026-05-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0007_opportunity_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="opportunity",
            name="numberOfOApplications",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
