# Generated by Django 6.0.5 on 2026-05-12 23:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("company", "0008_opportunity_numberofoapplications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="opportunity",
            name="Company",
        ),
        migrations.RemoveField(
            model_name="opportunity",
            name="numberOfOApplications",
        ),
    ]
